Add support for vmware

diff --git a/umbrel-dev b/umbrel-dev
--- a/umbrel-dev
+++ b/umbrel-dev
@@ -48,12 +48,14 @@ determine_provider() {
 # Check required dependencies are installed
 # If not, fail with instructions on how to fix
 check_dependencies() {
-  local deps
+  local deps=("git" "vagrant")
 
   if [[ "${PROVIDER}" == "virtualbox" ]]; then
-    deps=("git" "vagrant" "vboxmanage")
+    deps+=("vboxmanage")
   elif [[ "${PROVIDER}" == "parallels" ]]; then
-    deps=("git" "vagrant" "prlctl")
+    deps+=("prlctl")
+  elif [[ "${PROVIDER}" == "vmware_desktop" ]] || [[ "${PROVIDER}" == "vmware_fusion" ]]; then
+    deps+=("vmrun")
   fi
 
   for cmd in "${deps[@]}"; do
@@ -70,11 +72,24 @@ check_dependencies() {
         echo "  brew install --cask virtualbox"
       elif [[ "${cmd}" == "prlctl" ]]; then
         echo "  brew install --cask parallels"
+      elif [[ "${cmd}" == "vmrun" ]]; then
+        echo "  brew install --cask vmware-fusion"
       fi
       echo
       exit 1
     fi
   done
+
+  if [[ "${PROVIDER}" == "vmware_desktop" ]] || [[ "${PROVIDER}" == "vmware_fusion" ]]; then
+    if [[ ! -f "/opt/vagrant-vmware-desktop/certificates/vagrant-utility.client.crt" ]]; then
+      echo "  The Vagrant VMware utility is missing"
+      echo
+      echo "  To continue, please install it using:"
+      echo 
+      echo "  brew install --cask vagrant-vmware-utility"
+      exit 1
+    fi
+  fi
 }
 
 # Run a command inside the development VM
@@ -108,8 +123,7 @@ check_umbrel_dev_environment() {
   done
 }
 
-PROVIDER="${UMBREL_DEV_PROVIDER:-$(determine_provider)}"
-
+export PROVIDER="${UMBREL_DEV_PROVIDER:-$(determine_provider)}"
 export ARCH="${UMBREL_DEV_ARCH:-$(uname -m)}"
 
 # Check deps before running any commands
@@ -135,6 +149,8 @@ if [[ "$command" = "init" ]]; then
 
   if [[ "${PROVIDER}" == "parallels" ]]; then
     vagrant plugin install --local vagrant-parallels
+  elif [[ "${PROVIDER}" == "vmware_desktop" ]] || [[ "${PROVIDER}" == "vmware_fusion" ]]; then
+    vagrant plugin install --local vagrant-vmware-desktop
   fi
   
   vagrant plugin install --local vagrant-bindfs
